import type { NextPage } from 'next'
import Head from 'next/head'
import illustration from '../assets/images/illustration.svg'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <aside>

                </aside>
            </div>
        </>
    )
}

export default Home
